/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#0d0096",
        "on-surface": "#dae2fd",
        "inverse-surface": "#dae2fd",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#07006c",
        "secondary": "#4edea3",
        "on-secondary-container": "#00311f",
        "outline": "#908fa0",
        "surface-container-highest": "#2d3449",
        "surface-container-high": "#222a3d",
        "inverse-on-surface": "#283044",
        "surface-dim": "#0b1326",
        "on-primary": "#1000a9",
        "tertiary-fixed": "#ffdadb",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#ff516a",
        "surface-container": "#171f33",
        "primary-container": "#8083ff",
        "error-container": "#93000a",
        "on-tertiary": "#67001b",
        "on-surface-variant": "#c7c4d7",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#40000d",
        "error": "#ffb4ab",
        "surface": "#0b1326",
        "on-secondary": "#003824",
        "surface-container-lowest": "#060e20",
        "on-background": "#dae2fd",
        "tertiary": "#ffb2b7",
        "on-secondary-fixed": "#002113",
        "on-error": "#690005",
        "secondary-fixed-dim": "#4edea3",
        "surface-tint": "#c0c1ff",
        "inverse-primary": "#494bd6",
        "secondary-fixed": "#6ffbbe",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "secondary-container": "#00a572",
        "primary": "#c0c1ff",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed-dim": "#ffb2b7",
        "background": "#0b1326",
        "on-tertiary-fixed-variant": "#92002a",
        "outline-variant": "#464554",
        "surface-container-low": "#131b2e",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-container": "#5b0017"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}
